### ISSUE TITLE
Hi, I have some questions that I hope can be answered by you. Thanks!

### ISSUE THREAD

**Issue by wwduikaidh** [FCYtheFreeman/MDD_sMRI_classification_PyTorch#3]
What is the input size size of the data and what are the requirements for the list name and data for the csv form.

**Comment by wwduikaidh** [comment]
I would like to ask you about this data path, I see that in the opts.py file, the setting of Root directory path of data, is it to put all the nii images of train, val, test in the same folder?

**Comment by wwduikaidh** [comment]
![315d6f4543c7ffacbbaef7c13c6d67e](https://github.com/FCYtheFreeman/MDD_sMRI_classification_PyTorch/assets/120093958/cb374351-1190-44e7-98ed-42833e03cbc5)
![24e8dfbd1e1f0d2c64c9ee8d82437d6](https://github.com/FCYtheFreeman/MDD_sMRI_classification_PyTorch/assets/120093958/70827d8a-e309-4c66-bab1-46376fe2c564)
Here's a screenshot of where I store my images and set them up in the opts.py file

**Comment by wwduikaidh** [comment]
`Traceback (most recent call last):
  File "D:\pycharm\classification\MDD_sMRI_classification_PyTorch\main.py", line 112, in <module>
    run(fold_id, opt)
  File "D:\pycharm\classification\MDD_sMRI_classification_PyTorch\main.py", line 91, in run
    train_epoch(i, fold_id, train_loader, model, criterion, optimizer, opt,
  File "D:\pycharm\classification\MDD_sMRI_classification_PyTorch\train.py", line 21, in train_epoch
    for i ,(inputs,labels) in enumerate(data_loader):
  File "E:\envs\run\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\envs\run\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "E:\envs\run\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "E:\envs\run\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\envs\run\lib\site-packages\nibabel\loadsave.py", line 100, in load
    stat_result = os.stat(filename)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:/dataset/shiyan/nii/train/mwp1003_S_1021'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\envs\run\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\envs\run\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\envs\run\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\pycharm\classification\MDD_sMRI_classification_PyTorch\dataset.py", line 38, in __getitem__
    img = self.loader(fn)
  File "D:\pycharm\classification\MDD_sMRI_classification_PyTorch\dataset.py", line 14, in default_loader
    img_pil = nib.load(path)
  File "E:\envs\run\lib\site-packages\nibabel\loadsave.py", line 102, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'D:/dataset/shiyan/nii/train/mwp1003_S_1021'`


But this error appeared, I don't know what is the reason, I hope I can get your reply, thanks!
